export {
  type AuthEnv,
  type AuthUser,
  buildTokenMap,
  buildTokenMetadataMap,
  extractBearerToken,
  parseTokenScope,
  requireRole,
  requireSessionOrToken,
  requireTenantOwnership,
  resolveSessionUser,
  type ScopedTokenConfig,
  scopedBearerAuth,
  scopedBearerAuthWithTenant,
  scopeSatisfies,
  type TokenMetadata,
  type TokenScope,
  timingSafeMapLookup,
  validateTenantAccess,
  validateTenantOwnership,
} from "@wopr-network/platform-core/auth";
