export {
  type AuthType,
  auditCredentialEncryption,
  type CreateCredentialInput,
  type CredentialRow,
  type CredentialSummary,
  type CredentialSummaryRow,
  CredentialVaultStore,
  type DecryptedCredential,
  DrizzleCredentialRepository,
  DrizzleMigrationTenantKeyAccess,
  getVaultEncryptionKey,
  type ICredentialMigrationAccess,
  type ICredentialRepository,
  type ICredentialVaultStore,
  type IMigrationTenantKeyAccess,
  type MigrationResult,
  migratePlaintextCredentials,
  type PlaintextFinding,
  type RotateCredentialInput,
  type RotationResult,
  reEncryptAllCredentials,
} from "@wopr-network/platform-core/security";
